### ISSUE TITLE
Can't Convert wkb

### ISSUE THREAD

**Issue by zabralex85** [cschwarz/wkx-sharp#5]
![111](https://user-images.githubusercontent.com/13407732/48664663-21af9200-eab3-11e8-8e78-e285729b14e8.PNG)

wkb data: 0101000020E6100000C6284BCBD7C8E6BF96BD4B6D7A214340

**Comment by cschwarz** [comment]
You need to convert your hex string to a byte array first.

**Comment by zabralex85** [comment]
i tried with byte array in stream, not working.

**Comment by zabralex85** [comment]
result =>

using NetTopologySuite.IO;
using System;
using System.Linq;

namespace Localizador.Sherlog.Zones.Importer
{
    public class LatLng
    {
        public double Latitude { get; set; }
        public double Longitude { get; set; }

        public LatLng(string geom)
        {
            var bytes = StringToByteArray(geom);

            WKBReader reader = new WKBReader();
            var location = reader.Read(bytes);

            Latitude = location.Coordinate.X;
            Longitude = location.Coordinate.Y;
        }

        static byte[] StringToByteArray(string hex)
        {
            return Enumerable.Range(0, hex.Length)
                             .Where(x => x % 2 == 0)
                             .Select(x => Convert.ToByte(hex.Substring(x, 2), 16))
                             .ToArray();
        }
    }
}
