### ISSUE TITLE
Spatialite

### ISSUE THREAD

**Issue by dunha** [cschwarz/wkx-sharp#7]
Hi
Thanks for this very useful library
I find myself using the Spatialite format more often than EWKB and am looking at the possibility of adapting your library to include that format which is an extended EWKB if you like (see 
http://www.gaia-gis.it/gaia-sins/BLOB-Geometry.html).
I'm pretty confident I can manage a reader at least, but i don't have sufficient skills to follow your code completely enough, (particularly through the WkbReader.Read type variable and what that actually represents), to adapt your prototype and would have to bolt something less elegant onto it.
I was wondering if you  might have any plans to support this format yourself as it is gaining popularity or could provide some tips on the best way to go about it

Thanks

Duncan

**Comment by cschwarz** [comment]
Hi Duncan,

I don't have any plans to implement Spatialite support myself for now.

I would start by copying the WkbReader and debug through it with a well-known Spatialite BLOB.

Regards
Christian

**Comment by dunha** [comment]
Hi Christian
Thanks for the response. 
I started on that but lost my way a bit. I copied the EWKBReader, but hadn't thought about the WKBReader too. I'll give it a go

Thanks

Duncan

**Comment by dunha** [comment]
All working nicely. Thanks for the encouragement.
I'll have a look at the writer next, although my use case is mainly reading

Duncan
